In [1]:
import pandas as pd
import numpy as np

import json
import warnings
warnings.filterwarnings("ignore")

In [2]:
EXTERNAL_DATASET_PATH = "C:/Users/abhis/Downloads/datasets/External_Cibil_Dataset.xlsx"
INTERNAL_DATASET_PATH = "C:/Users/abhis/Downloads/datasets/Internal_Bank_Dataset.xlsx"
UNSEEN_DATASET_PATH = "C:/Users/abhis/Downloads/datasets/Unseen_Dataset.xlsx"

external_df = pd.read_excel(EXTERNAL_DATASET_PATH)
internal_df = pd.read_excel(INTERNAL_DATASET_PATH)
unseen_df = pd.read_excel(UNSEEN_DATASET_PATH)

In [3]:
external_df.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

In [4]:
internal_df.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32

In [5]:
unseen_df.head()

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,...,PL_Flag,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,MARITALSTATUS,EDUCATION,GENDER,last_prod_enq2,first_prod_enq2
0,0.000,0.0,0,0.000,0,0,0,4,1,4,...,1,0.000,0.0,1,0,Married,12TH,M,PL,PL
1,0.000,0.0,0,0.000,0,0,0,0,0,1,...,0,0.000,0.0,0,0,Single,GRADUATE,F,ConsumerLoan,ConsumerLoan
2,0.125,0.0,0,0.000,1,0,0,0,2,6,...,0,0.000,0.0,1,0,Married,SSC,M,ConsumerLoan,others
3,0.000,0.0,0,0.000,0,0,0,0,3,0,...,0,0.000,0.0,0,0,Married,POST-GRADUATE,M,AL,AL
4,0.000,0.0,1,0.167,0,0,0,0,6,0,...,0,0.429,0.0,1,0,Married,12TH,M,ConsumerLoan,PL

In [6]:
print(external_df.shape)
print(internal_df.shape)

(51336, 62)
(51336, 26)

In [7]:
print("External_df:", external_df.columns)
print()
print("Internal_df:", internal_df.columns)
print()
print("Unseen_df:", unseen_df.columns)

External_df: Index(['PROSPECTID', 'time_since_recent_payment',
       'time_since_first_deliquency', 'time_since_recent_deliquency',
       'num_times_delinquent', 'max_delinquency_level',
       'max_recent_level_of_deliq', 'num_deliq_6mts', 'num_deliq_12mts',
       'num_deliq_6_12mts', 'max_deliq_6mts', 'max_deliq_12mts',
       'num_times_30p_dpd', 'num_times_60p_dpd', 'num_std', 'num_std_6mts',
       'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt',
       'num_dbt_6mts', 'num_dbt_12mts', 'num_lss', 'num_lss_6mts',
       'num_lss_12mts', 'recent_level_of_deliq', 'tot_enq', 'CC_enq',
       'CC_enq_L6m', 'CC_enq_L12m', 'PL_enq', 'PL_enq_L6m', 'PL_enq_L12m',
       'time_since_recent_enq', 'enq_L12m', 'enq_L6m', 'enq_L3m',
       'MARITALSTATUS', 'EDUCATION', 'AGE', 'GENDER', 'NETMONTHLYINCOME',
       'Time_With_Curr_Empr', 'pct_of_active_TLs_ever',
       'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'CC_utilization',
       'CC_Flag', 'PL_utilization', 'PL_Flag', 'pct_PL_enq_L6m_of_L12m',
       'pct_CC_enq_L6m_of_L12m', 'pct_PL_enq_L6m_of_ever',
       'pct_CC_enq_L6m_of_ever', 'max_unsec_exposure_inPct', 'HL_Flag',
       'GL_Flag', 'last_prod_enq2', 'first_prod_enq2', 'Credit_Score',
       'Approved_Flag'],
      dtype='str')

Internal_df: Index(['PROSPECTID', 'Total_TL', 'Tot_Closed_TL', 'Tot_Active_TL',
       'Total_TL_opened_L6M', 'Tot_TL_closed_L6M', 'pct_tl_open_L6M',
       'pct_tl_closed_L6M', 'pct_active_tl', 'pct_closed_tl',
       'Total_TL_opened_L12M', 'Tot_TL_closed_L12M', 'pct_tl_open_L12M',
       'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'Auto_TL', 'CC_TL',
       'Consumer_TL', 'Gold_TL', 'Home_TL', 'PL_TL', 'Secured_TL',
       'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL'],
      dtype='str')

Unseen_df: Index(['pct_tl_open_L6M', 'pct_tl_closed_L6M', 'Tot_TL_closed_L12M',
       'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'CC_TL', 'Home_TL', 'PL_TL',
       'Secured_TL', 'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL',
       'Age_Newest_TL', 'time_since_recent_payment',
       'max_recent_level_of_deliq', 'num_deliq_6_12mts', 'num_times_60p_dpd',
       'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt',
       'num_dbt_12mts', 'num_lss', 'recent_level_of_deliq', 'CC_enq_L12m',
       'PL_enq_L12m', 'time_since_recent_enq', 'enq_L3m', 'NETMONTHLYINCOME',
       'Time_With_Curr_Empr', 'CC_Flag', 'PL_Flag', 'pct_PL_enq_L6m_of_ever',
       'pct_CC_enq_L6m_of_ever', 'HL_Flag', 'GL_Flag', 'MARITALSTATUS',
       'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2'],
      dtype='str')

In [8]:
# Merging the external and internal df based PROSPECTID
df = pd.merge(external_df, internal_df, on="PROSPECTID", how="inner")

In [9]:
df.shape

(51336, 87)

In [10]:
df['Approved_Flag'].value_counts(dropna=False)

Approved_Flag
P2    32199
P3     7452
P4     5882
P1     5803
Name: count, dtype: int64

In [11]:
# we'll convert Approved_Flag to binary target
df['target'] = df['Approved_Flag'].map(
    lambda x: 1 if x in ["P1", "P2"] else 0
)

df['target'].value_counts(dropna=False)

target
1    38002
0    13334
Name: count, dtype: int64

Target variable is slightly unbalanced, which is normal in credit datasets.

In [12]:
df.drop(columns="Approved_Flag", inplace=True)

In [13]:
# Extracting final feature list and storing it for training the model

final_features = list(unseen_df.columns)

In [14]:
print("Missing in train:", (set(final_features) - set(df.columns)))

Missing in train: set()

In [15]:
# Sorting
final_features = sorted(final_features)

In [16]:
x = df[final_features]
y = df['target']

In [17]:
print(len(final_features))
print(x.shape)

42
(51336, 42)

In [18]:
train_df = df[final_features + ['target']]

In [19]:
train_df['MARITALSTATUS'].value_counts(dropna=False)

MARITALSTATUS
Married    37752
Single     13584
Name: count, dtype: int64

In [22]:
# saving final_features and final training dataset
with open("../data/processed/final_features.json", "w") as f:
    json.dump(final_features, f)

In [24]:
train_df.to_parquet("../data/raw/train_df.parquet", index=False)
unseen_df.to_parquet("../data/raw/unseen_df.parquet", index=False)

In [30]:
final_features

['Age_Newest_TL',
 'Age_Oldest_TL',
 'CC_Flag',
 'CC_TL',
 'CC_enq_L12m',
 'EDUCATION',
 'GENDER',
 'GL_Flag',
 'HL_Flag',
 'Home_TL',
 'MARITALSTATUS',
 'NETMONTHLYINCOME',
 'Other_TL',
 'PL_Flag',
 'PL_TL',
 'PL_enq_L12m',
 'Secured_TL',
 'Time_With_Curr_Empr',
 'Tot_Missed_Pmnt',
 'Tot_TL_closed_L12M',
 'Unsecured_TL',
 'enq_L3m',
 'first_prod_enq2',
 'last_prod_enq2',
 'max_recent_level_of_deliq',
 'num_dbt',
 'num_dbt_12mts',
 'num_deliq_6_12mts',
 'num_lss',
 'num_std_12mts',
 'num_sub',
 'num_sub_12mts',
 'num_sub_6mts',
 'num_times_60p_dpd',
 'pct_CC_enq_L6m_of_ever',
 'pct_PL_enq_L6m_of_ever',
 'pct_tl_closed_L12M',
 'pct_tl_closed_L6M',
 'pct_tl_open_L6M',
 'recent_level_of_deliq',
 'time_since_recent_enq',
 'time_since_recent_payment']